### ISSUE TITLE
Yazeed Hathal Alotaibi-HW1

### ISSUE THREAD

**Issue by yazeedhathal** [misk-jsd2/03-conditionals-and-loops#1]
// First Question 99 Bottles of Coke:

for(var i = 99; i >=0; i--){
  
   if ( i == "0"){
    	console.log(i +" No more bottles of coke on the wall, no more bottles of coke. Go to the store and buy some more, 99 bottles of coke on the wall.");
 }
   else  if (i == "1"){
    		console.log(i +" Bottle of Coke on the Wall in the terminal. If you're unfamiliar with the song, you can find the lyrics below.");
    }
   
   else {console.log(i +" Bottles of Coke on the Wall in the terminal. If you're unfamiliar with the song, you can find the lyrics below.");}
   
}
// second  Question Random Address Generator:

var streetNum = [12,14,15,33,22];

var streetName = ['murphy street','wiesly street','mike street','yarrow street','jeffrerson street'];

var cityName = ['Rochester','Boston','Tyson corner','califfornia','ocland'];

var stateName= ['NY','VA','CA','MA','DC'];

var zipCode=['11213','12312','34312','45314','123421'];

var randomStreetNum = streetNum[(Math.floor(Math.random()*streetNum.length))];
var randomStreetName = streetName[(Math.floor(Math.random()*streetName.length))];
var randomCityname = cityName[(Math.floor(Math.random()*cityName.length))];
var randomStateName= stateName[(Math.floor(Math.random()*stateName.length))];
var randomZipCode= zipCode[(Math.floor(Math.random()*zipCode.length))];

// console.log(randomStreetNum+' '+randomStreetName +' '+randomCityname+' '+randomStateName+' '+randomZipCode);

// for (var i=0; i<= streetNum.length; i++)
// {
// 	console.log()

// }

// var random =[streetNum,stateName,cityName,stateName,zipCode];

// for(var i = 0 ; i<= random.length-1 ; i++){
// 		console.log(Math.floor(Math.random*random.length[i]));}

**Comment by morojAlh** [comment]
We discussed the homework one-on-one.
Good job 👍🏼
