### ISSUE TITLE
Mohammed ALsanad assignment 1

### ISSUE THREAD

**Issue by mohammedsanad** [misk-jsd2/03-conditionals-and-loops#12]
// Assignment 1: 99 Bottles of Coke
for(var i = 100; i> 1;i-- )
    {
      console.log((i-1)+" bottles of coke on the wall, "+(i-1)+"bottles of coke. Take one down and pass it around, "+(i-2)+" bottles
of coke on the wall.");
    }
console.log("No more bottles of coke on the wall, no more bottles of
coke. Go to the store and buy some more, 99 bottles of coke on the
wall.")

**Comment by morojAlh** [comment]
We discussed the homework one-on-one.
Good job 👍🏼
