### ISSUE TITLE
hamadalqarni-RandomAddresses

### ISSUE THREAD

**Issue by hamadalqarni** [misk-jsd2/03-conditionals-and-loops#16]
`
var numstreet=['34578','78515','95875','49258','15789'];
var namestreet=[' AAA Street',' BBB Street',' CCC Street ',' DDD Street',' EEE Street'];
var cityname=['Riyadh','Jeedah','Abha','Dammam','Tabuok'];
var statename=['SN A','SN B','SN C','SN D','SN E'];
var zipcode=['15365','58914','34987','12458','25496'];
var i=0;
var arrays=[numstreet,namestreet,cityname,statename,zipcode];

/*for (var i = 0; i <5 ; i++) //each element will print in new line
{
	console.log(arrays[i][Math.floor((Math.random() *arrays.length)]);
}*/

var a=arrays[0][Math.floor(Math.random()*arrays.length)];
var b=arrays[1][Math.floor(Math.random()*arrays.length)];
var c=arrays[2][Math.floor(Math.random()*arrays.length)];
var d=arrays[3][Math.floor(Math.random()*arrays.length)];
var e=arrays[4][Math.floor(Math.random()*arrays.length)];
console.log(a+b+', '+c+', '+d+', '+e);
`

**Comment by morojAlh** [comment]
We discussed the homework one-on-one.
Good job 👍🏼
