### ISSUE TITLE
Sultan Alqaedi

### ISSUE THREAD

**Issue by salqaedi0** [misk-jsd2/03-conditionals-and-loops#19]
var x = "bottles";
var num = 99;
while (num > 1) {
 console.log(num + " " + x + " of coke on the wall, "+num + " " + x + " of coke,"+"Take one down and pass it around,"+ (num-1) + " " + x + " of coke on the wall.");
 num = num - 1;
 if (num > 0) {

 }

 else {
 console.log("No more " + x + " of coke on the wall.");
}
var x1 = "bottle";
if (num <= 1) 
{
 console.log(num + " " + x1 + " of coke on the wall, "+num + " " + x1 + " of coke,"+"Take one down and pass it around,no more bottles of coke on the wall.");

 }
if (num == 0) 
{
 console.log("No more bottles of coke on the wall, no more bottles of coke. Go to the store and buy some more"+ " 99 bottles of coke on the wall.");

 }

}
------------------------------------------------------------------------------------------------
var streetNumber = ['3213', '25127', '98863', '98873'];

var streetName = ['A street', 'B street', 'C street', 'D street'];

var cityName = ['Riyadh', 'Dammam', 'Jedda', 'Tabouk'];

var stateName = ['Qassem State', 'North State', 'East State', 'South State'];

var zipCode = ['28889', '96459', '35748', '15005'];
var RA = [];
for (var i = 0; i <= 4 ; i++)
{
RA.push (Math.floor(Math.random()*3));
}
console.log (streetNumber[RA[0]] + streetName[RA[1]] + cityName[RA[2]] + stateName[RA[3]] + zipCode[RA[4]]);

**Comment by morojAlh** [comment]
We discussed the homework one-on-one.
Good job 👍🏼
