### ISSUE TITLE
Yasser Alghunaim

### ISSUE THREAD

**Issue by alghunaimyasser** [misk-jsd2/03-conditionals-and-loops#6]
// The Random Address

var streetNo = [16,340,22];
var streetName = [" King Fahad Street,"," Ring Road Street,"," Alorubah Street,"];
var cityName= [" Riyadh,"," AlQassim,"," Dammam,"];
var zipcode= [" 44506"," 22032"," 13001"];
var random = [];
for (var i = 0 ; i <= 3 ; i++)
{
random.push(Math.floor(Math.random()*3));

}
console.log(streetNo[random[0]] + streetName[random[1]] + cityName[random[2]] + zipcode[random[3]]);

// The bottles game
for (var i = 99 ; i >= 0 ; i--)
{
if (i >= 3)
{
    console.log(i + " bottles of coke on the wall, " + i + "  bottles of coke. Take one down and pass it around, " + (i-1) + " bottles of coke on the wall.");
}
if (i == 2)
{
    console.log(i + " bottles of coke on the wall, " + i + "  bottles of coke. Take one down and pass it around, " + (i-1) + " bottle of coke on the wall.");
}
if (i == 1)
{
    console.log(i + " bottle of coke on the wall, " + i + "  bottle of coke. Take one down and pass it around, "  + " no more bottles of coke on the wall.");
}
}

**Comment by morojAlh** [comment]
We discussed the homework one-on-one.
Good job 👍🏼
